apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 500m
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: default
#   namespace: default
#   annotations:
#     volume.alpha.kubernetes.io/storage-class: default
# spec:
#   accessModes: [ReadWriteOnce]
#   resources:
#     requests:
#       cpu: 500m
#       storage: 5Gi
